// <auto-generated />
namespace eGradjevina.WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _migracija : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_migracija));
        
        string IMigrationMetadata.Id
        {
            get { return "201710082102041__migracija"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
